[package]
name = "glee"
version = "0.1.1"
authors = ["Oussama <md.oussama@gmail.com>"]

[dependencies]
webgl = { git = "https://github.com/oussama/webgl-rs"}
error-chain = "*"
byteorder = "*"
serde = "*"
serde_derive = "*"
bincode = "*"
arrayvec = "*"
