[package]
name = "glee"
version = "0.1.1"
authors = ["Oussama <md.oussama@gmail.com>"]

[dependencies]
webgl = { path = "../webgl"}
error-chain = "*"
byteorder = "*"
serde = "*"
serde_derive = "*"
bincode = "*"
arrayvec = "*"
