[package]
name = "glee"
version = "0.1.0"
authors = ["Oussama <md.oussama@gmail.com>"]

[dependencies]
glenum = "*"
webgl = { path = "C:/Users/oussa/work/webgl-rs"}
error-chain = "*"
byteorder = "*"
serde = "*"
serde_derive = "*"
bincode = "*"
arrayvec = "*"
